### ISSUE TITLE
ReadMe 파일 정리

### ISSUE THREAD

**Issue by diaa-woo** [KimWang906/OS_Learning_with_Rust#1]
공부하는 걸 마크다운 파일에 정리해주는 거는 매우 좋아!
그런데 보통 ReadMe 파일은 사람들에게 이 소스파일은 대표적으로 어떤 기능을 담고 있고, 어떻게 사용할 수 있는지 알 수 있게 해주는 어찌보면 이 오픈소스 저장소의 대표 레퍼런스라고 볼 수 있거든?
그래서 매일 공부하는 거를 ReadMe 파일보다는 따로 폴더를 만들어서 day1.md 등등으로 마크다운으로 정리해서 놔두는게 더 좋을거 같아! ReadMe 파일에는 링크만 걸어주고

깃허브 올리는거 보고 솔직히 놀랐습니다... 굉장히 유망한 후배네! 앞으로도 응원한다 화이팅!

**Comment by KimWang906** [comment]
넵 감사합니다
